# -*- coding: utf-8 -*-
"""ejercicio_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11d4tKphHuJhUdwUcl0K5WprC5fjLwbSa
"""

class Vendedor:

    #Clase que modela a un vendedor con nombre, apellidos y edad.

    def __init__(self, nombre, apellidos):
        self.nombre = nombre
        self.apellidos = apellidos
        self.edad = None

    def imprimir(self):

        #Datos del vendedor.

        print(f"Nombre del vendedor = {self.nombre}")
        print(f"Apellidos del vendedor = {self.apellidos}")
        print(f"Edad del vendedor = {self.edad}")

    def verificar_edad(self, edad):

        #Verifica si la edad es correcta, si no es correcta lanza una excepción.

        if edad < 18:
            raise ValueError("El vendedor debe ser mayor de 18 años.")
        elif edad < 0 or edad > 120:
            raise ValueError("La edad no puede ser negativa ni mayor a 120.")
        else:
            self.edad = edad


def main():

    nombre = input("Nombre del vendedor: ")
    apellidos = input("Apellidos del vendedor: ")

    try:
        edad = int(input("Edad del vendedor: "))
        vendedor = Vendedor(nombre, apellidos)
        vendedor.verificar_edad(edad)
        vendedor.imprimir()
    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()