# -*- coding: utf-8 -*-
"""ejercicio_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11d4tKphHuJhUdwUcl0K5WprC5fjLwbSa
"""

def main():
    # Primer bloque try
    try:
        print("Ingresando al primer try")
        cociente = 10000 / 0  # Esto lanza una excepción
        print("Después de la división")  # Nunca se ejecuta
    except ZeroDivisionError as e:
        print("División por cero")  # Se captura y se imprime este mensaje
    finally:
        print("Ingresando al primer finally")  # Siempre se ejecuta

    # Segundo bloque try
    try:
        print("Ingresando al segundo try")
        objeto = None
        objeto.toString()  # Esto lanza una excepción de tipo AttributeError
        print("Imprimiendo objeto")  # Nunca se ejecuta
    except ZeroDivisionError:
        print("División por cero")
    except Exception as e:
        print("Ocurrió una excepción")  # Se captura aquí
    finally:
        print("Ingresando al segundo finally")  # Siempre se ejecuta

# Ejecutar el programa
main()

